add_graph_cuda_executable(pagerank pagerank basic/pagerank.cu)
add_graph_cuda_executable(pagerank_queue pagerank tolerance_queue/pagerank_tolerance_queue.cu)
add_graph_mpi_nccl_executable(pagerank_multiGPU pagerank multigpu/pagerank_tolerance_multiGPU.cu)
add_graph_mpi_nccl_executable(pagerank_multiGPU_basic pagerank multigpu_basic/pagerank_multiGPU_basic.cu)

target_link_libraries(pagerank_queue PRIVATE CUDA::nvtx3)
target_link_libraries(pagerank_multiGPU PRIVATE CUDA::nvtx3)
