/**
 * @file cc_tolerance_multiGPU.cuh
 * @brief Distributed CC with selective DMR and asynchronous CPU checks.
 */
#ifndef CC_TOLERANCE_MULTIGPU_CUH
#define CC_TOLERANCE_MULTIGPU_CUH

#include <cuda_runtime.h>
#include <mpi.h>
#include <nccl.h>

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <mutex>
#include <thread>
#include <vector>

#include "include/distributed_benchmark.cuh"
#include "include/distributed_partition.cuh"
#include "include/spsc_queue.h"

/** Number of reusable device/host slots used by the asynchronous checker. */
static constexpr int CC_ASYNC_CHECK_BUFFER_COUNT = 64;

/**
 * @brief Per-iteration fault-detection summary produced by the CC kernel.
 *
 * The structure deliberately contains only aggregate data, so one asynchronous
 * D2H copy transfers a fixed, small payload regardless of graph size.
 */
struct CcDistributedCheckInfo {
    int dmr_error_flag;
    int monotonic_error_flag;
    unsigned long long sum_abs_delta;
    int count_update;
};

/** @brief Host-side copy of one completed iteration's detection summary. */
struct CcAsyncCheckResult {
    bool done = false;
    unsigned long long sum_abs_delta = 0;
    int count_update = 0;
    int dmr_error = 0;
    int monotonic_error = 0;
};

/** @brief Queue item associating a CUDA transfer event with its iteration. */
struct CcAsyncCheckTask {
    int iter = 0;
    int buffer = -1;
};

/**
 * @brief Scores active owned vertices and marks the critical subset for DMR.
 *
 * @param active Owned-vertex activity array; -1 means inactive, 1 normal, 2 critical.
 * @param values Owned-and-ghost component labels (only owned indices are scored).
 * @param row_offsets CSR offsets for outgoing edges of owned vertices.
 * @param owned_count Number of vertices owned by this MPI rank.
 * @param max_outdegree Global maximum out-degree used to normalize the score.
 * @param alpha Weight of the degree score.
 * @param beta Weight of the current-label score.
 * @param threshold Critical-vertex cutoff.
 * @param count Receives the number of active owned vertices visited by the kernel.
 */
__global__ void ccDistributedScoreAndMarkKernel(
    int* active,
    const int* values,
    const int* row_offsets,
    int owned_count,
    int max_outdegree,
    float alpha,
    float beta,
    float threshold,
    int* count
) {
    int v = blockIdx.x * blockDim.x + threadIdx.x;
    if (v >= owned_count || active[v] == -1) return;

    atomicAdd(count, 1);
    int outdegree = row_offsets[v + 1] - row_offsets[v];
    int safe_max = max_outdegree > 0 ? max_outdegree : 1;
    float value_score = 1.0f / (1.0f + fabsf((float)values[v]));
    float score = alpha * ((float)outdegree / (float)safe_max) + beta * value_score;
    active[v] = (score >= threshold) ? 2 : 1;
}

/**
 * @brief Performs one distributed label-propagation step with detection metadata.
 *
 * Active threads compute the normal CC update. Idle threads in the same block
 * independently recompute critical vertices and flag DMR disagreement. The
 * kernel also flags an unexpected label decrease and accumulates the absolute
 * label delta used by the later CPU trend check. Only owned labels are written;
 * ghost labels remain read-only caches refreshed by NCCL after the kernel.
 *
 * Active and assigned redundant lanes select an owned compute vertex before
 * entering one common owned-plus-ghost pull loop. Role divergence is limited
 * to target selection, result placement, comparison, and primary writeback.
 *
 * @warning Block barriers do not create a grid-wide value snapshot. Other
 * blocks may update owned labels between primary and redundant reads, so a DMR
 * mismatch can occur without a hardware fault.
 *
 * @param values Local label array laid out as owned vertices followed by ghosts.
 * @param row_offsets Outgoing CSR offsets for owned vertices.
 * @param column_indices Outgoing neighbor local IDs.
 * @param column_offsets Incoming CSC offsets for owned vertices.
 * @param row_indices Incoming neighbor local IDs.
 * @param active Activity/criticality state for owned vertices.
 * @param update Owned-and-ghost activation flags generated by changed labels.
 * @param owned_count Number of owned vertices.
 * @param local_node_count Number of owned plus ghost vertices.
 * @param check_info Per-iteration aggregate written by the kernel.
 */
__global__ void ccDistributedToleranceKernel(
    int* values,
    const int* row_offsets,
    const int* column_indices,
    const int* column_offsets,
    const int* row_indices,
    const int* active,
    int* update,
    int owned_count,
    int local_node_count,
    CcDistributedCheckInfo* check_info
) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    int local_tid = threadIdx.x;

    __shared__ int critical_list[DG_BLOCK_SIZE];
    __shared__ int redundant_results[DG_BLOCK_SIZE];
    __shared__ int idle_count;
    __shared__ int critical_count;

    if (local_tid == 0) {
        idle_count = 0;
        critical_count = 0;
    }
    __syncthreads();

    bool valid = tid < owned_count;
    bool is_active = valid && active[tid] != -1;
    bool critical = is_active && active[tid] == 2;
    bool idle = !valid || !is_active;

    int critical_id = -1;
    int idle_id = -1;
    if (critical) {
        critical_id = atomicAdd(&critical_count, 1);
        if (critical_id < DG_BLOCK_SIZE) critical_list[critical_id] = tid;
    }
    if (idle) idle_id = atomicAdd(&idle_count, 1);
    __syncthreads();

    int old_value = valid ? values[tid] : 0;
    const bool does_redundant_work =
        idle && idle_id >= 0 && idle_id < critical_count &&
        idle_id < DG_BLOCK_SIZE;
    int compute_vertex = -1;
    if (is_active) {
        compute_vertex = tid;
    } else if (does_redundant_work) {
        compute_vertex = critical_list[idle_id];
    }

    int computed_value = 0;
    if (compute_vertex >= 0) {
        computed_value = values[compute_vertex];
        for (int e = column_offsets[compute_vertex];
             e < column_offsets[compute_vertex + 1]; ++e) {
            int src = row_indices[e];
            if (src >= 0 && src < local_node_count &&
                values[src] > computed_value) {
                computed_value = values[src];
            }
        }
    }

    int new_value = old_value;
    if (is_active) {
        new_value = computed_value;
    } else if (does_redundant_work) {
        redundant_results[idle_id] = computed_value;
    }
    __syncthreads();

    if (critical && critical_id >= 0 && critical_id < idle_count &&
        critical_id < DG_BLOCK_SIZE && redundant_results[critical_id] != new_value) {
        atomicExch(&check_info->dmr_error_flag, 1);
    }
    __syncthreads();

    if (!valid) return;
    if (!is_active) return;

    values[tid] = new_value;
    int diff = new_value - old_value;
    if (diff != 0) {
        atomicAdd(&check_info->sum_abs_delta, (unsigned long long)llabs((long long)diff));
        atomicAdd(&check_info->count_update, 1);
    }
    if (new_value > old_value) {
        for (int e = row_offsets[tid]; e < row_offsets[tid + 1]; ++e) {
            int dst = column_indices[e];
            if (dst >= 0 && dst < local_node_count) update[dst] = 1;
        }
    } else if (new_value < old_value) {
        atomicExch(&check_info->monotonic_error_flag, 1);
    }
}

/**
 * @brief Runs fault-detecting connected components across MPI ranks and GPUs.
 *
 * Each rank owns a contiguous vertex partition and caches remote neighbors as
 * ghosts. The compute stream preserves the original label propagation,
 * activation exchange, and value exchange order. Detection summaries are copied
 * through a fixed pool of pinned buffers on a separate stream; a background CPU
 * worker consumes completed copies without calling MPI. After computation, the
 * main thread drains the worker and collectively reduces per-iteration DMR,
 * monotonicity, and average-delta-trend results.
 *
 * Detection is observational only: an error flag does not roll back or repair
 * labels. If all check buffers are busy, that iteration still computes normally
 * using a scratch summary but is omitted from the entire final anomaly report.
 *
 * @param h_value Output array receiving one component label per global vertex.
 * @param h_row_offsets Global outgoing CSR offsets.
 * @param h_column_indices Global outgoing CSR neighbor IDs.
 * @param h_column_offsets Global incoming CSC offsets.
 * @param h_row_indices Global incoming CSC neighbor IDs.
 * @param num_nodes Number of global vertices.
 * @param num_edges Number of global edges (unused by the partitioned routine).
 * @param alpha Degree-score weight used to select DMR-critical vertices.
 * @param beta Label-score weight used to select DMR-critical vertices.
 * @param threshold Critical-vertex score cutoff.
 *
 * @pre MPI has been initialized with at least MPI_THREAD_FUNNELED.
 * @pre Every rank supplies the same graph and num_nodes is at least the rank count.
 */
inline void ccMultiGPU(
    int* h_value,
    const int* h_row_offsets,
    const int* h_column_indices,
    const int* h_column_offsets,
    const int* h_row_indices,
    int num_nodes,
    int num_edges,
    float alpha = 0.5f,
    float beta = 0.5f,
    float threshold = 0.3f
) {
    (void)num_edges;

    int mpi_initialized = 0;
    MPI_Initialized(&mpi_initialized);
    if (!mpi_initialized) {
        fprintf(stderr, "ccMultiGPU 需要先调用 MPI_Init。\n");
        exit(EXIT_FAILURE);
    }

    int rank = 0;
    int world_size = 1;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    int device = dg_select_rank_device();
    ncclComm_t comm = dg_create_nccl_comm(rank, world_size);

    std::vector<DgSubgraphHost> parts;
    dg_build_all_subgraphs(world_size, num_nodes, h_row_offsets, h_column_indices,
                           h_column_offsets, h_row_indices, parts);
    const DgSubgraphHost& part = parts[rank];

    if (rank == 0) {
        printf("发现 %d 个 MPI rank，开启 NCCL 分布式 CC 容错版本。\n", world_size);
    }
    printf("Rank %d GPU %d: owned [%d, %d), owned_count=%d, local_count=%d, ghosts=%zu\n",
           rank, device, part.start_node, part.end_node, part.owned_count,
           part.local_node_count, part.ghost_global_ids.size());

    std::vector<std::vector<DgPeerPlanHost>> host_plans;
    dg_build_peer_plans(parts, world_size, num_nodes, host_plans);
    std::vector<DgPeerPlanDevice> plans;
    dg_upload_peer_plans(host_plans, rank, world_size, plans, false);

    int max_outdegree = 1;
    for (int v = 0; v < num_nodes; ++v) {
        int outdegree = h_row_offsets[v + 1] - h_row_offsets[v];
        if (outdegree > max_outdegree) max_outdegree = outdegree;
    }

    int *d_values = nullptr, *d_row_offsets = nullptr, *d_column_indices = nullptr;
    int *d_column_offsets = nullptr, *d_row_indices = nullptr, *d_active = nullptr;
    int *d_update = nullptr, *d_active_count = nullptr;
    CcDistributedCheckInfo* d_check_info_scratch = nullptr;
    std::vector<CcDistributedCheckInfo*> d_check_info(CC_ASYNC_CHECK_BUFFER_COUNT, nullptr);
    std::vector<CcDistributedCheckInfo*> h_check_info(CC_ASYNC_CHECK_BUFFER_COUNT, nullptr);
    std::vector<cudaEvent_t> compute_done_events(CC_ASYNC_CHECK_BUFFER_COUNT);
    std::vector<cudaEvent_t> check_done_events(CC_ASYNC_CHECK_BUFFER_COUNT);

    CUDA_CHECK(cudaMalloc(&d_values, part.local_node_count * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_row_offsets, (part.owned_count + 1) * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_column_indices, part.column_indices.size() * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_column_offsets, (part.owned_count + 1) * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_row_indices, part.row_indices.size() * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_active, part.owned_count * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_update, part.local_node_count * sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_active_count, sizeof(int)));
    CUDA_CHECK(cudaMalloc(&d_check_info_scratch, sizeof(CcDistributedCheckInfo)));
    for (int buffer = 0; buffer < CC_ASYNC_CHECK_BUFFER_COUNT; ++buffer) {
        CUDA_CHECK(cudaMalloc(&d_check_info[buffer], sizeof(CcDistributedCheckInfo)));
        CUDA_CHECK(cudaMallocHost(&h_check_info[buffer], sizeof(CcDistributedCheckInfo)));
        CUDA_CHECK(cudaEventCreateWithFlags(
            &compute_done_events[buffer], cudaEventDisableTiming));
        CUDA_CHECK(cudaEventCreateWithFlags(
            &check_done_events[buffer], cudaEventDisableTiming));
    }

    std::vector<int> h_local_value(part.local_node_count);
    for (int lv = 0; lv < part.local_node_count; ++lv) h_local_value[lv] = part.local_to_global[lv];
    std::vector<int> h_active(part.owned_count, 1);

    CUDA_CHECK(cudaMemcpy(d_values, h_local_value.data(), part.local_node_count * sizeof(int), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_row_offsets, part.row_offsets.data(), (part.owned_count + 1) * sizeof(int), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_column_indices, part.column_indices.data(), part.column_indices.size() * sizeof(int), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_column_offsets, part.column_offsets.data(), (part.owned_count + 1) * sizeof(int), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_row_indices, part.row_indices.data(), part.row_indices.size() * sizeof(int), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_active, h_active.data(), part.owned_count * sizeof(int), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemset(d_update, 0xff, part.local_node_count * sizeof(int)));

    cudaStream_t stream, check_stream;
    CUDA_CHECK(cudaStreamCreate(&stream));
    CUDA_CHECK(cudaStreamCreateWithFlags(&check_stream, cudaStreamNonBlocking));
    dg_nccl_exchange_int_values(d_values, plans, world_size, rank, comm, stream);
    CUDA_CHECK(cudaStreamSynchronize(stream));

    // The main thread consumes free slots and produces pending tasks. The worker
    // performs the inverse operations, making both queues strictly SPSC.
    SpscQueue<int, CC_ASYNC_CHECK_BUFFER_COUNT> free_buffers;
    SpscQueue<CcAsyncCheckTask, CC_ASYNC_CHECK_BUFFER_COUNT> pending_tasks;
    for (int buffer = 0; buffer < CC_ASYNC_CHECK_BUFFER_COUNT; ++buffer) {
        free_buffers.try_push(buffer);
    }

    std::atomic<bool> stop_check_worker(false);
    std::mutex pending_mutex;
    std::condition_variable pending_cv;
    std::vector<CcAsyncCheckResult> check_results(1001);

    // Sleep while no task exists, then block in CUDA until the oldest D2H copy
    // completes. This avoids a polling thread stealing CPU time from MPI.
    std::thread check_worker([&]() {
        CUDA_CHECK(cudaSetDevice(device));
        while (true) {
            CcAsyncCheckTask task;
            {
                std::unique_lock<std::mutex> lock(pending_mutex);
                pending_cv.wait(lock, [&]() {
                    return stop_check_worker.load(std::memory_order_acquire) ||
                           !pending_tasks.empty();
                });
                if (stop_check_worker.load(std::memory_order_acquire) &&
                    pending_tasks.empty()) {
                    break;
                }
                if (!pending_tasks.try_pop(task)) continue;
            }

            CUDA_CHECK(cudaEventSynchronize(check_done_events[task.buffer]));
            CcAsyncCheckResult result;
            result.done = true;
            result.dmr_error = h_check_info[task.buffer]->dmr_error_flag;
            result.monotonic_error =
                h_check_info[task.buffer]->monotonic_error_flag;
            result.sum_abs_delta = h_check_info[task.buffer]->sum_abs_delta;
            result.count_update = h_check_info[task.buffer]->count_update;
            if (task.iter >= 0 && task.iter < (int)check_results.size()) {
                check_results[task.iter] = result;
            }
            free_buffers.try_push(task.buffer);
        }
    });

    DgIterationPhaseTimer phase_timer;
    GraphCudaEventAccumulator graph_kernel_timer;
    CUDA_CHECK(graph_cuda_timer_create(&graph_kernel_timer));
    DgBenchmarkTiming timing;
    int iter = 0;
    int total_active = num_nodes;
    const auto main_loop_start = std::chrono::steady_clock::now();

    while (iter < 1000 && total_active > 0) {
        ++iter;
        phase_timer.start_pre(stream);
        int check_buffer = -1;
        bool do_async_check = free_buffers.try_pop(check_buffer);
        CcDistributedCheckInfo* iteration_check_info = do_async_check
            ? d_check_info[check_buffer]
            : d_check_info_scratch;

        CUDA_CHECK(cudaMemsetAsync(d_active_count, 0, sizeof(int), stream));
        ccDistributedScoreAndMarkKernel<<<dg_blocks(part.owned_count), DG_BLOCK_SIZE, 0, stream>>>(
            d_active, d_values, d_row_offsets, part.owned_count, max_outdegree,
            alpha, beta, threshold, d_active_count);
        CUDA_CHECK(cudaGetLastError());

        CUDA_CHECK(cudaMemsetAsync(
            iteration_check_info, 0, sizeof(CcDistributedCheckInfo), stream));
        CUDA_CHECK(graph_cuda_timer_start(&graph_kernel_timer, stream));
        ccDistributedToleranceKernel<<<dg_blocks(part.owned_count), DG_BLOCK_SIZE, 0, stream>>>(
            d_values, d_row_offsets, d_column_indices, d_column_offsets, d_row_indices,
            d_active, d_update, part.owned_count, part.local_node_count,
            iteration_check_info);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(graph_cuda_timer_stop(&graph_kernel_timer, stream));

        CUDA_CHECK(cudaMemsetAsync(d_active, 0xff, part.owned_count * sizeof(int), stream));
        dgCopyOwnedUpdateKernel<<<dg_blocks(part.owned_count), DG_BLOCK_SIZE, 0, stream>>>(
            d_update, d_active, part.owned_count);
        CUDA_CHECK(cudaGetLastError());

        if (do_async_check) {
            // The compute event protects the device summary. The transfer event
            // protects its pinned host slot until the worker returns that slot.
            CUDA_CHECK(cudaEventRecord(compute_done_events[check_buffer], stream));
            CUDA_CHECK(cudaStreamWaitEvent(
                check_stream, compute_done_events[check_buffer], 0));
            CUDA_CHECK(cudaMemcpyAsync(
                h_check_info[check_buffer],
                d_check_info[check_buffer],
                sizeof(CcDistributedCheckInfo),
                cudaMemcpyDeviceToHost,
                check_stream));
            CUDA_CHECK(cudaEventRecord(check_done_events[check_buffer], check_stream));
            {
                std::lock_guard<std::mutex> lock(pending_mutex);
                if (!pending_tasks.try_push({iter, check_buffer})) {
                    fprintf(stderr, "CC async check queue invariant failed.\n");
                    exit(EXIT_FAILURE);
                }
            }
            pending_cv.notify_one();
        }
        phase_timer.stop_pre(stream);

        phase_timer.start_comm(stream);
        dg_nccl_exchange_activation(d_update, d_active, plans, world_size, rank, comm, stream);
        dg_nccl_exchange_int_values(d_values, plans, world_size, rank, comm, stream);
        phase_timer.stop_comm(stream);

        phase_timer.start_post(stream);
        CUDA_CHECK(cudaMemsetAsync(d_update, 0xff, part.local_node_count * sizeof(int), stream));
        CUDA_CHECK(cudaMemsetAsync(d_active_count, 0, sizeof(int), stream));
        dgCountActiveKernel<<<dg_blocks(part.owned_count), DG_BLOCK_SIZE, 0, stream>>>(
            d_active, d_active_count, part.owned_count);
        CUDA_CHECK(cudaGetLastError());

        int local_active = 0;
        CUDA_CHECK(cudaMemcpyAsync(
            &local_active, d_active_count, sizeof(int),
            cudaMemcpyDeviceToHost, stream));
        phase_timer.stop_post(stream);
        CUDA_CHECK(cudaStreamSynchronize(stream));
        phase_timer.accumulate(timing.gpu_compute_ms, timing.nccl_exchange_ms);
        CUDA_CHECK(graph_cuda_timer_accumulate(&graph_kernel_timer));

        dg_timed_allreduce(
            &local_active, &total_active, 1, MPI_INT, MPI_SUM,
            MPI_COMM_WORLD, timing.mpi_sync_ms);
    }

    timing.main_loop_ms = dg_elapsed_ms(
        main_loop_start, std::chrono::steady_clock::now());

    // Only unfinished checker work belongs to the drain phase. Detection-result
    // collectives are measured separately below.
    const auto drain_start = std::chrono::steady_clock::now();
    {
        std::lock_guard<std::mutex> lock(pending_mutex);
        stop_check_worker.store(true, std::memory_order_release);
    }
    pending_cv.notify_one();
    if (check_worker.joinable()) check_worker.join();
    timing.cpu_check_drain_ms = dg_elapsed_ms(
        drain_start, std::chrono::steady_clock::now());

    const auto postcheck_start = std::chrono::steady_clock::now();

    bool detected_dmr = false;
    bool detected_monotonic = false;
    bool detected_avg_increase = false;
    int first_dmr_iter = -1;
    int first_monotonic_iter = -1;
    int first_avg_increase_iter = -1;
    int checked_iteration_count = 0;
    bool have_previous_avg_delta = false;
    double previous_avg_delta = 0.0;

    for (int check_iter = 1; check_iter <= iter; ++check_iter) {
        int local_done = check_results[check_iter].done ? 1 : 0;
        int all_done = 0;
        dg_timed_allreduce(
            &local_done, &all_done, 1, MPI_INT, MPI_MIN,
            MPI_COMM_WORLD, timing.postcheck_mpi_ms);
        if (!all_done) continue;
        ++checked_iteration_count;

        unsigned long long local_sum = check_results[check_iter].sum_abs_delta;
        unsigned long long global_sum = 0;
        int local_count = check_results[check_iter].count_update;
        int global_count = 0;
        int local_dmr = check_results[check_iter].dmr_error ? 1 : 0;
        int global_dmr = 0;
        int local_monotonic = check_results[check_iter].monotonic_error ? 1 : 0;
        int global_monotonic = 0;

        dg_timed_allreduce(
            &local_sum, &global_sum, 1, MPI_UNSIGNED_LONG_LONG, MPI_SUM,
            MPI_COMM_WORLD, timing.postcheck_mpi_ms);
        dg_timed_allreduce(
            &local_count, &global_count, 1, MPI_INT, MPI_SUM,
            MPI_COMM_WORLD, timing.postcheck_mpi_ms);
        dg_timed_allreduce(
            &local_dmr, &global_dmr, 1, MPI_INT, MPI_LOR,
            MPI_COMM_WORLD, timing.postcheck_mpi_ms);
        dg_timed_allreduce(
            &local_monotonic, &global_monotonic, 1, MPI_INT, MPI_LOR,
            MPI_COMM_WORLD, timing.postcheck_mpi_ms);

        if (global_dmr) {
            detected_dmr = true;
            if (first_dmr_iter < 0) first_dmr_iter = check_iter;
        }
        if (global_monotonic) {
            detected_monotonic = true;
            if (first_monotonic_iter < 0) first_monotonic_iter = check_iter;
        }
        if (global_count > 0) {
            double average_delta =
                (double)global_sum / (double)global_count;
            if (have_previous_avg_delta && average_delta > previous_avg_delta) {
                detected_avg_increase = true;
                if (first_avg_increase_iter < 0) {
                    first_avg_increase_iter = check_iter;
                }
            }
            previous_avg_delta = average_delta;
            have_previous_avg_delta = true;
        }
    }

    timing.postcheck_total_ms = dg_elapsed_ms(
        postcheck_start, std::chrono::steady_clock::now());
    timing.graph_kernel_ms = graph_kernel_timer.total_ms;
    dg_report_benchmark_timing(timing, rank, world_size);

    std::vector<int> h_owned(part.owned_count);
    CUDA_CHECK(cudaMemcpy(h_owned.data(), d_values, part.owned_count * sizeof(int), cudaMemcpyDeviceToHost));
    std::vector<int> counts = dg_owned_counts(world_size, num_nodes);
    std::vector<int> displs = dg_displacements(counts);
    MPI_Allgatherv(h_owned.data(), part.owned_count, MPI_INT,
                   h_value, counts.data(), displs.data(), MPI_INT, MPI_COMM_WORLD);

    if (rank == 0) {
        printf("异步CPU检测(CC): DMR=%d, monotonic=%d, avg_delta_increase=%d\n",
               detected_dmr ? 1 : 0,
               detected_monotonic ? 1 : 0,
               detected_avg_increase ? 1 : 0);
        if (first_dmr_iter >= 0 || first_monotonic_iter >= 0 ||
            first_avg_increase_iter >= 0) {
            printf(
                "首次检测迭代(CC): DMR=%d, monotonic=%d, avg_delta_increase=%d\n",
                first_dmr_iter,
                first_monotonic_iter,
                first_avg_increase_iter);
        }
        printf("异步检测覆盖(CC): checked=%d/%d, skipped=%d\n",
               checked_iteration_count, iter, iter - checked_iteration_count);
        printf("NCCL 分布式 CC 容错版本迭代 %d 次结束。\n", iter);
        printf("BENCHMARK_ITERATIONS iterations=%d\n", iter);
    }

    phase_timer.destroy();
    CUDA_CHECK(graph_cuda_timer_destroy(&graph_kernel_timer));
    CUDA_CHECK(cudaStreamDestroy(check_stream));
    CUDA_CHECK(cudaStreamDestroy(stream));
    dg_free_peer_plans(plans);
    cudaFree(d_values);
    cudaFree(d_row_offsets);
    cudaFree(d_column_indices);
    cudaFree(d_column_offsets);
    cudaFree(d_row_indices);
    cudaFree(d_active);
    cudaFree(d_update);
    cudaFree(d_active_count);
    cudaFree(d_check_info_scratch);
    for (int buffer = 0; buffer < CC_ASYNC_CHECK_BUFFER_COUNT; ++buffer) {
        cudaFree(d_check_info[buffer]);
        cudaFreeHost(h_check_info[buffer]);
        cudaEventDestroy(compute_done_events[buffer]);
        cudaEventDestroy(check_done_events[buffer]);
    }
    NCCL_CHECK(ncclCommDestroy(comm));
}

#endif
